name: avto_test_mobil
description: "Road Test mobil ilovasi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  audioplayers: ^6.4.0
  video_player: ^2.9.5
  chewie: ^1.8.5
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
